author: Jorge Gomez Rivas <jorgegomezrivas@gmail.com>
license:
  header: |
    Use of this source code is governed by an MIT-style license that can be
    found in the LICENSE file at https://github.com/open-arch/openarch-cli/
  text: MIT
